trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

stages:
- stage: Build
  jobs:
  - job: Build_Store_Packages
    pool:
      vmImage: 'vs2017-win2016'
    condition: ne(variables['Build.Reason'], 'PullRequest')
    steps:
    - script: 'dotnet run --project "./scripts/CTime2.Scripts/CTime2.Scripts.csproj" -- build-store-package'
      displayName: Build Store Packages

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Test Package'
      inputs:
        PathtoPublish: 'artifacts/TestPackage.zip'
        ArtifactName: 'Test Package'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Store Package'
      inputs:
        PathtoPublish: 'artifacts/StorePackage.zip'
        ArtifactName: 'StorePackage'

  - job: Build_PR
    pool:
      vmImage: 'vs2017-win2016'
    condition: eq(variables['Build.Reason'], 'PullRequest')
    steps:
    - script: 'dotnet run --project "./scripts/CTime2.Scripts/CTime2.Scripts.csproj" -- build'
      displayName: Build PR