name: Build Store Package

on:
  push: 
    tags: 
      - "v*"

jobs:
  Build:
    runs-on: windows-latest
    steps: 

    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Disable dotnet welcome message
      run: New-Item -Force "$env:USERPROFILE/.dotnet/$(dotnet --version).dotnetFirstUseSentinel" | Out-Null

    - name: Build
      run: dotnet run --project "./scripts/CTime2.Scripts/CTime2.Scripts.csproj" -- build-store-package

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload TestPackage.zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/TestPackage.zip
        asset_name: TestPackage.zip
        asset_content_type: application/zip

    - name: Upload StorePackage.zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/StorePackage.zip
        asset_name: StorePackage.zip
        asset_content_type: application/zip